---

- name: Include tasks to get information about the vCenter.
  ansible.builtin.include_tasks:
    file: "get_vcenter_info.yml"

- name: Assert that vCenter version is supported
  ansible.builtin.assert:
    that:
      - ansible_role_vsphere_snapshot_vcenter_about_info.about_info.version is version('7', '>=')
      - ansible_role_vsphere_snapshot_vcenter_about_info.about_info.version is version('9', '<')
    msg: "This role only supports vSphere versions 7 and 8."
    quiet: true

- name: Assert that instance UUID is not empty
  ansible.builtin.assert:
    that:
      - vsphere_snapshot_vm_instance_uuid is defined
      - vsphere_snapshot_vm_instance_uuid | default('', true) | length > 0
    msg: "The instance UUID (vsphere_snapshot_vm_instance_uuid) is required but was not provided."
    quiet: true
  when: vsphere_snapshot_action is defined

- name: Assert that snapshot name prefix and suffix combined length is within limits
  ansible.builtin.assert:
    that:
      - ((vsphere_snapshot_name_prefix | default('', true)) | length) + ((vsphere_snapshot_name_suffix | default('', true)) | length) <= 44
    msg: "The combined length of prefix and suffix must be less than or equal to 44 characters to fit within VMware's 80-character snapshot name limit."
    quiet: true

- name: Include tasks to check the virtual machine's capabilities before snapshot operations
  ansible.builtin.include_tasks:
    file: "check_capabilities.yml"
  when: vsphere_snapshot_action | lower in ['create', 'remove', 'revert']

- name: Include tasks to {{ vsphere_snapshot_action }} a VMware snapshot
  ansible.builtin.include_tasks:
    file: "{{ vsphere_snapshot_action | lower }}.yml"
